---

# !!! WARNING !!!
#
# Before modifiyng PLEASE read the documenation
# and make sure that you completly understand what
# means each step and how it impacts other steps
#
# !!! WARNING !!!

# This option allows to control health check step
# Use this option with caution
health_check: true

# Perform force apt-get update
apt_update: false

# Action for customized packages which were installed not from
# specified repositories(uknown packages).
# Since it is useless to get diff for unknown package and
# somtimes it is impossible.
#
# Possible values:
# - "fail"      (default)
# - "keep"      (don't update these packages)
# - "reinstall" (update these packages, lost current packages)
# - any other mean "fail"
unknown_custom_pkgs: "fail"

# Action for upgradable packages which were installed not from
# specified repositories(unknown packages).
#
# Possible values:
# - "fail"      (default)
# - "keep"      (don't update these packages)
# - "reinstall" (update these packages, lost current packages)
# - any other mean "fail"
unknown_upgradable_pkgs: "fail"

# Perform force gathering customizations
gather_customizations: false

# Which packet should be used for verification
# - Installed
# - Candidate
#
# If you want istall MU you shoud use 'Candidate'
# If you want just appy new patch on the current installation
# you need to use 'Installed' and enable 'use_current_customizations"
pkg_ver_for_verification: "Candidate"

# Ignore already applied patches
# Disable by default since it might be double checked for avoiding any issues
ignore_applied_patches: false
