---

mos_dir:                  "/root/mos_mu"
backup_dir:               "{{ mos_dir }}/backup"
report_dir:               "{{ mos_dir }}/report"
custom_dir:               "{{ mos_dir }}/customizations"
patches_dir:              "{{ mos_dir }}/patches"
verification_dir:         "{{ mos_dir }}/verification"
apt_dir:                  "{{ mos_dir }}/apt"
apt_conf:                 "{{ apt_dir }}/apt.conf"
apt_src_dir:              "{{ apt_dir }}/sources.list.d"

fuel_backup_dir:          "/root/fuel_mos_mu/fuel_backup"
fuel_dir:                 "/root/fuel_mos_mu/env_{{ env_id }}"
fuel_report_dir:          "{{ fuel_dir }}/report"
fuel_custom_dir:          "{{ fuel_dir }}/customizations"
fuel_custom_backup_dir:   "{{ fuel_dir }}/customizations_backup"
fuel_patches_dir:         "{{ fuel_dir }}/patches"
fuel_custom_verification: "{{ fuel_dir }}/customizations_verification"
fuel_unified_dir:         "{{ fuel_dir }}/customizations_unified"

keep_pkgs:                ""
srcs_list_tmpl:           "sources.list.j2"
