---

- hosts: env_{{ env_id }}
  any_errors_fatal: true
  vars:
      steps: "update_ceph"

  vars_files:
    - "vars/ceph.yml"
    - "vars/common.yml"
    - "vars/mos_releases/{{ mos_release }}.yml"
    - "vars/steps/{{ steps }}.yml"

  tasks:
    - name: Check if CEPH is deployed on this env
      local_action: shell fuel node --env-id {{ env_id }} | grep ceph-osd
      run_once: true
      ignore_errors: true
      register: ceph_exist

    - name: Exit, if CEPH is not deployed on the env
      fail:
        msg: >
            "Exiting update_ceph.yml playbook, CEPH is not deployed on this env."
      run_once: true
      when:
        - ceph_exist.rc != 0

    - include: tasks/health_checks.yml
      when: health_check is undefined or
            health_check

    - name: create ceph_repo
      apt_repository:
        repo={{ ceph_repo }}
        state=present
        update_cache=yes
      when:
        - add_ceph_repo is defined
        - add_ceph_repo
        - ceph_repo is defined


- hosts: env_{{ env_id }}:&controller
  any_errors_fatal: true
  serial: 1
  vars:
      steps: "update_ceph"

  vars_files:
    - "vars/ceph.yml"
    - "vars/common.yml"
    - "vars/steps/{{ steps }}.yml"

  tasks:
    - include: tasks/update_ceph.yml

  post_tasks:
    - include: tasks/restart_ceph.yml
      vars:
        restart_mon: "yes"
      when:
        - restart_ceph is defined
        - restart_ceph

- hosts: env_{{ env_id }}:&ceph-osd
  any_errors_fatal: true
  serial: 1
  vars:
      steps: "update_ceph"

  vars_files:
    - "vars/ceph.yml"
    - "vars/common.yml"
    - "vars/steps/{{ steps }}.yml"

  pre_tasks:
    - name: set osd flags
      command: ceph osd set {{ item }}
      with_items:
        - noout
        - noscrub
        - nodeep-scrub
      delegate_to: "{{ groups['controller'][0] }}"

  tasks:
    - include: tasks/update_ceph.yml

  post_tasks:
    - include: tasks/restart_ceph.yml
      vars:
        restart_osd: "yes"
      when:
        - restart_ceph is defined
        - restart_ceph


- hosts: env_{{ env_id }}:&controller
  any_errors_fatal: true
  serial: 1
  vars:
      steps: "update_ceph"

  vars_files:
    - "vars/ceph.yml"
    - "vars/common.yml"
    - "vars/steps/{{ steps }}.yml"

  tasks:

    - name: Update radosgw package
      apt: name=radosgw
        state=latest
        update_cache=yes

  post_tasks:
    - include: tasks/restart_ceph.yml
      vars:
        restart_rgw: "yes"
      when:
        - restart_ceph is defined
        - restart_ceph


- hosts: env_{{ env_id }}:!controller:!ceph-osd
  any_errors_fatal: true
  vars:
      steps: "update_ceph"

  vars_files:
    - "vars/ceph.yml"
    - "vars/common.yml"
    - "vars/steps/{{ steps }}.yml"

  tasks:
    - include: tasks/update_ceph.yml
