---

env_release: "8.0"
fuel_url: "http://mirror.fuel-infra.org/mos-repos/ubuntu"
apt_repos:
  - name: "GA"
    url: "{{ fuel_url }}/{{ env_release }}"
    repo: "mos{{ env_release }}"
    type: "main restricted"
  - name: "mu-1"
    url: "{{ fuel_url }}/{{ env_release }}-mu-1"
    repo: "mos{{ env_release }}-updates"
    type: "main restricted"
  - name: "mu-2"
    url: "{{ fuel_url }}/{{ env_release }}-mu-2"
    repo: "mos{{ env_release }}-updates"
    type: "main restricted"
  - name: "mu-3"
    url: "{{ fuel_url }}/{{ env_release }}-mu-3"
    repo: "mos{{ env_release }}-updates"
    type: "main restricted"
apt_sources_lists:
  - name: "fuel"
    path: "/etc/apt/sources.list.d/mos.list"


controller_pcs_resources:
    - p_heat-engine
    - p_neutron-l3-agent
    - p_neutron-vpn-agent
    - p_neutron-plugin-openvswitch-agent
    - p_neutron-dhcp-agent
    - p_neutron-metadata-agent
    - p_ceilometer-agent-central
    - p_ceilometer-alarm-evaluator

controller_services:
    - heat-api
    - heat-api-cfn
    - heat-api-cloudwatch
    - nova-api
    - nova-cert
    - nova-conductor
    - nova-scheduler
    - nova-novncproxy
    - nova-objectstore
    - nova-consoleauth
    - cinder-api
    - cinder-scheduler
    - cinder-volume
    - cinder-backup
    - glance-api
    - glance-registry
    - neutron-server
    - ceilometer-api
    - ceilometer-collector
    - ceilometer-alarm-notifier
    - ceilometer-agent-notification
    - sahara-api
    - sahara-engine
    - murano-api
    - murano-engine
    - apache2

compute_services:
    - nova-compute
    - neutron-l3-agent
    - neutron-plugin-openvswitch-agent
    - neutron-metadata-agent
    - ceilometer-agent-compute
    - cinder-volume
    - cinder-backup
    - libvirtd

