---
snapshot_repo: "9.2"
snapshot_suite: "mos9.0-updates"

env_release: "9.0"
fuel_url: "http://mirror.fuel-infra.org/mos-repos/ubuntu"
apt_repos:
  - name: "9.0"
    url: "{{ fuel_url }}/{{ env_release }}"
    repo: "mos{{ env_release }}"
    type: "main restricted"
  - name: "9.1"
    url: "{{ fuel_url }}/9.1"
    repo: "mos{{ env_release }}-updates"
    type: "main restricted"
  - name: "9.2"
    url: "{{ fuel_url }}/{{ snapshot_repo }}"
    repo: "mos{{ env_release }}-updates"
    type: "main restricted"
apt_sources_lists:
  - name: "fuel"
    path: "/etc/apt/sources.list.d/mos.list"

mos92_repos:
  - name: "mos9.2-updates"
    url: "{{ fuel_url }}/{{ snapshot_repo }}"
    suite: "{{ snapshot_suite }}"
    section: "main restricted"
    type: "deb"
    priority: 1050
  - name: "mos9.2-security"
    url: "{{ fuel_url }}/{{ snapshot_repo }}"
    suite: "mos9.0-security"
    section: "main restricted"
    type: "deb"
    priority: 1050
  - name: "mos9.2-holdback"
    url: "{{ fuel_url }}/{{ snapshot_repo }}"
    suite: "mos9.0-holdback"
    section: "main restricted"
    type: "deb"
    priority: 1100


controller_pcs_resources:
    - p_heat-engine
    - neutron-openvswitch-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-l3-agent
    - p_ceilometer-agent-central
    - p_ceilometer-alarm-evaluator

controller_services:
    - heat-api
    - heat-api-cfn
    - heat-api-cloudwatch
    - nova-api
    - nova-cert
    - nova-conductor
    - nova-scheduler
    - nova-novncproxy
    - nova-objectstore
    - nova-consoleauth
    - cinder-api
    - cinder-scheduler
    - cinder-volume
    - cinder-backup
    - glance-api
    - glance-registry
    - neutron-server
    - ceilometer-api
    - ceilometer-collector
    - ceilometer-alarm-notifier
    - ceilometer-agent-notification
    - sahara-api
    - sahara-engine
    - murano-api
    - murano-engine
    - apache2

compute_services:
    - nova-compute
    - neutron-l3-agent
    - neutron-plugin-openvswitch-agent
    - neutron-metadata-agent
    - ceilometer-agent-compute
    - cinder-volume
    - cinder-backup
    - libvirtd

fuel_services:
    - astute
    - cobblerd
    - mcollective
    - nailgun
    - nginx
    - openstack-keystone
    - ostf
    - rabbitmq-server
    - oswl_flavor_collectord
    - oswl_image_collectord
    - oswl_keystone_user_collectord
    - oswl_tenant_collectord
    - oswl_vm_collectord
    - oswl_volume_collectord
    - receiverd
    - statsenderd
    - assassind

